universe = vanilla

output = output/genre_$(genre).out

error = error/genre_$(genre).err

log = log/genre_$(genre).log

executable = genres.sh

arguments = main_dataset_$(genre).csv

transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/el8/python310.tar.gz, packages.tar.gz, corr_script.py, main_dataset_$(genre).csv

request_cpus = 1
request_memory = 1GB
request_disk = 1GB

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue genre from all_genres.txt
